# What I Learned From a Failed Backtesting of a GOLD Pair Trading Strategy

Trading strategies cannot be profitable if they aren't any mean reverting
or trending patterns underlying.
Otherwise you think you are trading but instead you are just random walking.

It's very hard to find a single stock deviates from its mean and revert
back to mean but it's much more often we see a pair or a series of stocks
back to its mean level.

In this blog, we use data to falisy not confirm. We want to test whether the 
pair trading of GLD and GDX will make profit.

## Data
We download data from 20060523 to 20071130 to form the training and testing data set.
This dataset's historical price is adjusted for splits but not for dividends and capital gains.

## Model
### Deisgn

### Evaluation
## Profit Analysis

## Action
### Act Action(What works)growth rate in different days

Tricks to compute annual compounding 
### Act NonAction(What doesn't work)
### Nonact Action(Future Directions)
How to find the data sources? 

## Stories and Lessons
Trading strategies can only be profitable if they are mean reverting or trending,
otherwise you are just random walking in the market.


## History

## Mathematical Tools
1. Total Least Squares and Orthogonal Regression
2. Sharpe Ratio and why it can be wrong?

## Markets and Instruments

